### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sam920829** [ItzLightyHD/Express#6]
(node:10020) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\boss\node_modules\discord.js\src\client\websocket\WebSocketManager.js:135:26)
    at Client.login (C:\Users\boss\node_modules\discord.js\src\client\Client.js:221:21)
(node:10020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ItzLightyHD** [comment]
Are you using the Heroku method? Or just the binaries?

**Comment by sam920829** [comment]
?

**Comment by ItzLightyHD** [comment]
> ?

I mean for the bot deploying

**Comment by sam920829** [comment]
no

**Comment by ItzLightyHD** [comment]
> no

You probably provided an invalid token, you don't need to quote the token
